changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "🧹 Maintenance"
      labels:
        - dependencies
        - chore
    - title: "Other Changes"
      labels:
        - "*"
